version: '3.1'

services:
  lobsters-db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=lobsters
    volumes:
      - db-data:/var/lib/mysql

  lobsters:
    build: .
    image: guillaumebriday/lobsters-docker
    environment:
      - RAILS_SERVE_STATIC_FILES=true
    ports:
      - "3000:3000"
    depends_on:
      - lobsters-db

volumes:
  db-data:
